name: Generate TVKing EPG

on:
  workflow_dispatch:
  push:
    paths:
      - fetch_schedule.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install requests beautifulsoup4

    - name: Run fetch_schedule.py
      run: python fetch_schedule.py

    - name: Upload generated XML
      uses: actions/upload-artifact@v4
      with:
        name: tvking_epg
        path: tvking_epg.xml
